[fixing-ts-errors] TS2322: Type 'IconType' is not assignable to type 'FC<SVGProps<SVGSVGElement>>'.
src/Components/Tutorial/index.tsx:613:9 - error TS2322: Type 'IconType' is not assignable to type 'FC<SVGProps<SVGSVGElement>>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'SVGProps<SVGSVGElement>' is not assignable to type 'IconBaseProps' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
      Types of property 'color' are incompatible.
        Type 'string | undefined' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.

613         icon={BarcodeIcon}
            ~~~~

  node_modules/flowbite-react/lib/esm/components/FormControls/TextInput/TextInput.d.ts:14:5
    14     icon?: FC<ComponentProps<'svg'>>;
           ~~~~
    The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & TextInputProps & RefAttributes<HTMLInputElement>'

src/Components/Tutorial/index.tsx:910:29 - error TS2322: Type 'IconType' is not assignable to type 'FC<SVGProps<SVGSVGElement>>'.

910                             icon={BarcodeIcon}
                                ~~~~

  node_modules/flowbite-react/lib/esm/components/FormControls/TextInput/TextInput.d.ts:14:5
    14     icon?: FC<ComponentProps<'svg'>>;
           ~~~~
    The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & TextInputProps & RefAttributes<HTMLInputElement>'