[fixing-ts-errors] TS6133: 'rest' is declared but its value is never read.
src/Components/Tutorial/index.tsx:131:6 - error TS6133: 'rest' is declared but its value is never read.

131   ...rest
         ~~~~