[fixing-ts-errors] TS6133: Unused React imports
src/App.test.tsx:1:1 - error TS6133: 'React' is declared but its value is never read.

1 import React from 'react';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/App.tsx:1:1 - error TS6133: 'React' is declared but its value is never read.

1 import React from 'react';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~