[fixing-ts-errors] TS6133: variable is declared but its value is never read.
src/Components/Tutorial/index.tsx:249:14 - error TS6133: 'result' is declared but its value is never read.

249       .then((result) => {
                 ~~~~~~

src/Components/Tutorial/index.tsx:252:15 - error TS6133: 'error' is declared but its value is never read.

252       .catch((error) => {
                  ~~~~~